In [2]:
pip install numpy

# NumPy

In [3]:
import numpy as np

### Arreglos

In [6]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [8]:
arr = np.array(([1,2,3], [4,5,6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
arr = np.array(([1,2,3], [4,5,6], [7,8,9]))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
arr = np.array([1,2,3,4,5,6,7], ndmin=3)

print(arr.ndim)

print(arr)
print(arr[0]) #con el inidice 0 veremos nuestra 1ra dimension
print(arr[0][0]) #Seria el 1er arreglo de nuetra 1ra dimension 
print(arr[0][0][0]) #Seria el 1er valor de nuestro 1er arreglo de nuestra 1ra dimension

3
[[[1 2 3 4 5 6 7]]]
[[1 2 3 4 5 6 7]]
[1 2 3 4 5 6 7]
1


In [14]:
arr = np.zeros((2,2))

print(arr)

[[0. 0.]
 [0. 0.]]


In [16]:
arr = np.ones((3,3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
arr = np.random.rand(3,3)
print(arr)

[[0.89046874 0.56584072 0.05949583]
 [0.03204449 0.46408597 0.1418725 ]
 [0.00350705 0.57033946 0.63052156]]


### Operaciones

In [19]:
arr1 = [1,2,3]

arr2 = [4,5,6]

arr3 = np.add(arr1, arr2)

print(arr3)

[5 7 9]


In [21]:
arr2 = [1,2,3]

arr1 = [4,5,6]

arr3 = np.subtract(arr1, arr2)

print(arr3)

[3 3 3]


In [22]:
arr2 = [1,2,3]

arr1 = [4,5,6]

arr3 = np.multiply(arr1, arr2)

print(arr3)

[ 4 10 18]


In [23]:
arr2 = [1,2,3]

arr1 = [4,5,6]

arr3 = np.divide(arr1, arr2)

print(arr3)

[4.  2.5 2. ]


### Agregacion

In [26]:
arr = [1,5,7]

media = np.mean(arr)

print(media)

4.333333333333333


In [27]:
arr = [1,5,7]

mediana = np.median(arr)

print(mediana)

5.0


In [29]:
arr = [1,5,7]

maximo = np.max(arr)

print(maximo)

7


In [30]:
arr = [1,5,7]

minmo = np.min(arr)

print(minmo)

1


### Indexacion

In [32]:
arr = np.array([1,2,3,4,5,6,7,8])

print(arr[0])


1


In [33]:
arr = np.array([1,2,3,4,5,6,7,8])

print(arr[-1])

8


In [35]:
arr = np.array(([1,2,3],[4,5,6]))

print(arr[1,2])

6


### Slicing

In [37]:
arr = np.array([1,2,3,4,5,6])

print(arr[1:4])

[2 3 4]


In [41]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[1:4:2])

[2 4]


In [42]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[::2])

[1 3 5 7 9]
